### PR TITLE
enhancments in dashboards (decimals, line interpolation)

### PR DESCRIPTION
**Pull request by daniel-w00**
- Changed decimal to 1 in charge session and charge dashboard as in #284 discussed
- the duration column in the charges table is to small, so days in the total cell are not displayed. I changed to left aligned but maybe bigger width would be good.
- for panels with variable time range which then can include times with offline state, linear line interpolation looked wired and step after was best. For fixed time range like in charge session or trip details linear or smooth is fine too and maybe looks a bit better
(iteration property is removed in new grafana version)

### CODE REVIEW

**Comment by daniel-w00** [comment]
In the charges table, the arrow for sorting not displayed for some columns because it is too small. Is it on purpose? The arrow isn't really important, it works without it
(not changed in this PR)

**Comment by tillsteinbach** [comment]
Yes, regarding the duration I did not think about charging more than 24hours. I think it is best to make the cell a little bit wider.

About the interpolation: I just think the step is more honest. Everything that is interpolating is somehow faking something.

For the decimals I just thought it is best to do rounding in the query and set the decimals to „auto“. Then we can have the more precise value when the user added the exact value while the estimates one has less decimals.

**Comment by daniel-w00** [comment]
Okay, agree with the interpolation.
Yes, auto decimal and do it in query is a good idea.
TODO:
- decimal for amount and power in charges and charge session 
- duration width charges table

**Comment by tillsteinbach** [comment]
hmm, with auto decimal it is doing strange things, e.g. it formats 5.8 as 5.80

**Pull request closed without merging**
