### PR TITLE
Check for vehicle data freshness in /healthcheck endpoint

### PR DESCRIPTION
**Pull request by lari**
Hi, I'm not expecting you to merge this as is, but rather opening a discussion on what would be a good way to determine the "health" of the service. I'm having an issue where `vwsfriend_vwsfriend_1` container stops updating the vehicle status (perhaps related to https://github.com/tillsteinbach/VWsFriend/issues/49). I've traced to issue to be that the "Updating data from WeConnect" loop freezes: https://github.com/tillsteinbach/VWsFriend/blob/4780ec76bb275f818168bec8cc5e14a5d4d08ff8/vwsfriend/vwsfriend/vwsfriend.py#L197-L207

The underlying issue is that something freezes (a network request?) in the weconnect package. However, the `/healthcheck` endpoint still returns `'ok'`, so this does not flag the container as unhealthy and thus it cannot be restarted automatically.

I've solved this for now by adding a check in the `/healthcheck` endpoint for vehicle data freshness. I.e. if the time since the most recent `Vehicle.lastUpdate` (or "last update from server") is more than twice the update interval, it will return an error, indicating that the service is not healthy. I'll then automatically restart the container with the following configuration in my `docker-compose.yml`:

```
restart: unless-stopped
healthcheck:
      test: ["CMD-SHELL", "(wget -qO- --tries=3 --timeout=5 --wait=60 --waitretry=0 --retry-connrefused --retry-on-http-error=400,500  http://localhost:4000/healthcheck | grep 'ok' -q) || bash -c 'kill -s 15 -1 && (sleep 10; kill -s 9 -1)'"]
      interval: 60s
      timeout: 4m
```
PS. `exit 1` in the healthcheck command would simply flag the container as unhealthy, and the restarting should be managed by some other service. With `kill` the container is actually shutdown and the `restart: unless-stopped` will trigger a restart. See: https://stackoverflow.com/a/64041910

### CODE REVIEW

**Comment by tillsteinbach** [comment]
Hey! First big thanks for your contribution and opening up a discussion. Are you sure that the loop freezes? I have not seen that before and if that is the case I would like to rather fix that first.
I like your idea to improve the heath check, the way you implemented has the problem that it does not work in an installation without a database (e.g. ABRP or HomeKit only). Also this would make the container unhealthy when the VW servers don't respond.
What actually should already happen is that when the servers do not respond that the script retries it after the next interval.

**Comment by lari** [comment]
Hi, I agree. It would be better to fix the actual issue. I tried to debug it but decided that it's faster for me to make a temporary fix by adjusting the health check for now, and thought that this might be useful for somebody else too. But I did not consider those other cases. So this would still need more work to determine the actual reason for not having fresh data.

Maybe this PR can be closed and I'll try to do some more debugging with the issue (e.g. adding more verbose logs to see where it exactly happens). I'll create a new issue once I have more info.

**Comment by MattiJarvinen** [comment]
How about when update is successful or server request fails a transient "health-check" file is touch:ed. 

Health check would compare current timestamp to the file's stat return value. If file doesn't exist do nothing if it's too old return false.

File is removed during start up to prevent infinite reboot loop.

Ok, complex but could prove useful if logged. It could throw a hint on what is going on.

**Comment by tillsteinbach** [comment]
Could be easier: There can be a variable in vwsfriend that is updated in the loop with the current timestamp. The health check endpoint that is now returning ok could check that this timestamp is not outdated more than interval + some margin. If it is it just returns an error. But still I think it is preferable to understand why it gets stuck on your installation

**Comment by tillsteinbach** [comment]
As this is stale, I close it. If there is anything new we can reopen it.

**Pull request closed without merging**
