### PR TITLE
Fix range value issue

### PR DESCRIPTION
**Pull request by bendavidson**
Since updating to software 3.2, the car consitently reports a drop in range equal to the conversion from kilometres to miles immediatately after a charge finishes and also at random times when the car's been idle for a number of hours.  These incorrect ranges are visible in the VW app so the bug is on VW's side.

This PR ignores these incorrect range changes when deciding whether to insert the latest weconnect data into the battery & ranges tables

image

### CODE REVIEW

**Comment by tillsteinbach** [comment]
Hey, quick question, is that a british car?

**Comment by bendavidson** [comment]
Hi,

Yes it is - I'm guessing this bug of VW's doesn't happen with euro based
cars?

Ben

**Comment by tillsteinbach** [comment]
I would prefer this to be fixed in the underlying API, like here: https://github.com/tillsteinbach/WeConnect-python/blob/3ffc890371a98490740debe8909a2da459fa3917/weconnect/elements/battery_status.py#L33 this way all apps using the API will be fixed

**Comment by bendavidson** [comment]
Sorry, I clearly haven't looked at how the weconnect-python stuff works
properly!  I was understanding it to have only the snapshot of data as
returned by the API at that moment in time.

I'll put a copy of this repro on my dev machine and have a play around with
it.

**Comment by tillsteinbach** [comment]
No problem, I would fix it myself, but I‘m very busy and that would take some time until I can find some time.

**Comment by bendavidson** [comment]
Good news - a variation of this on the battery_status element worked.  I think I'll add in an extra check to see only ignore the range value if the SOC has stayed the same which is the fingerprint of this error.

Got it in a fork of Weconnect-python [https://github.com/bendavidson/WeConnect-python](url)

Need to add the same to the range status, but needs a bit more thinking about as there are 3 values to consider.
Hopefully should have  PR ready by the end of the week

**Comment by bendavidson** [comment]
I've submitted a PR to the weconnect-python project.  I've tested it for a couple of days in parallel to the production one and it seems good.

Still a potential loophole if you restart the vwsfriend service while the API is reporting an invalid range as there is no data persistance in weconnect-python if the consuming service is not running but I think it's an acceptable compromise?

**Pull request closed without merging**
